# Target specific macros
TARGET = datalogging
TARGET_SOURCES = \
	dist_nx.c \
	PID.c \
	datalogging.c 

TOPPERS_OSEK_OIL_SOURCE = ./datalogging.oil

# Don't modify below part
O_PATH ?= build
include ../../nxtOSEK/ecrobot/ecrobot.mak
